name: Deploy MultiK8s
on:
  push:
    branches:
      - master
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          echo "{{ secrets.DOCKER_USERNAME }}"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t tws9797/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true tws9797/react-test npm test
 
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-373507
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: asia-southeast1-a
 
      # - name: Build
      #   run: |-
      #     docker build -t tws9797/multi-client-k8s-gh:latest -t tws9797/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
      #     docker build -t tws9797/multi-server-k8s-pgfix-gh:latest -t tws9797/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
      #     docker build -t tws9797/multi-worker-k8s-gh:latest -t tws9797/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      # - name: Push
      #   run: |-
      #     docker push tws9797/multi-client-k8s-gh:latest
      #     docker push tws9797/multi-server-k8s-pgfix-gh:latest
      #     docker push tws9797/multi-worker-k8s-gh:latest
 
      #     docker push tws9797/multi-client-k8s-gh:${{ env.SHA }}
      #     docker push tws9797/multi-server-k8s-pgfix-gh:${{ env.SHA }}
      #     docker push tws9797/multi-worker-k8s-gh:${{ env.SHA }}
 
      # - name: Apply
      #   run: |-
      #     kubectl apply -f k8s
      #     kubectl set image deployments/server-deployment server=tws9797/multi-server-k8s-pgfix-gh:${{ env.SHA }}
      #     kubectl set image deployments/client-deployment client=tws9797/multi-client-k8s-gh:${{ env.SHA }}
      #     kubectl set image deployments/worker-deployment worker=tws9797/multi-worker-k8s-gh:${{ env.SHA }}
